server:
  port: 8082

spring:
  application:
    name: GitHubRepoFetcher

github:
  fetcher:
    http:
      client:
        config:
          uri: https://api.github.com
          token: ${GITHUB_TOKEN}
          connectionTimeout: 5000
          readTimeout: 5000